### ISSUE TITLE
Missing weight file in "FitzHugh-Nagumo neural mass model" tutorial

### ISSUE THREAD

**Issue by sbrincat** [Neuroblox/NeurobloxDocsHost#11]
Tutorial code includes the line:
`weights = CSV.read("../data/weights.csv",DataFrame)`

Not sure if this file was supposed to have been created by some previous step or I messed something up, but it doesn’t exist anywhere on my HD???

**Comment by sbrincat** [comment]
OK, I did find this in the docs source now....

But -- and maybe I'm completely misunderstanding something fundamental here -- don't we want this to be accessible to users cutting and pasting the tutorial code snippets from the website into a notebook or IDE, and not require users to clone the whole documentation repo for it work?

**Comment by harisorgn** [comment]
>don't we want this to be accessible to users cutting and pasting the tutorial code snippets from the website into a notebook or IDE, and not require users to clone the whole documentation repo for it work?

Absolutely. Let's replace the included file with a matrix that we define. Looks like the connections on that example are sparse, so it won't be too verbose to do.
