### ISSUE TITLE
Add tutorial package dependencies to Neuroblox install?

### ISSUE THREAD

**Issue by sbrincat** [Neuroblox/NeurobloxDocsHost#13]
When running the tutorials on a new Julia install, I got package import errors (`ArgumentError: Package <package> not found in current path`) for all packages used in the tutorials (currently DifferentialEquations, Graphs, MetaGraphs, Plots, CSV, DataFrames, HypothesisTests).

Easily solved via running a bunch of Pkg.add(<package>), but I feel like this could potentially lose a bunch of users if they hit a bunch of errors right off the bat.

Is there any way to add these dependencies to whatever the Julia equivalent of a setup.py is, so these are automatically installed with Neuroblox?  I imagine most of these are central to using Neuroblox anyway, so we will want users to have them installed.

Or alternatively, if I was supposed to have installed Julia via some Anaconda-esque route that automatically installs popular numerical/analytics packages, we should definitely direct users to do that.

**Comment by sbrincat** [comment]
I see now that these are all already in the Project.toml, so I guess this issue becomes:
Make it obvious how we expect users to run these tutorials so all the dependencies get installed.

**Comment by harisorgn** [comment]
- we should make it explicit on the tutorial text that we are using other packages that people can easily add with `Pkg.add`. This way we briefly mention why we are using these other packages.
- more importantly, we should think more about why we need these packages and turn their desired functionalities into Neuroblox features or just reexport their functions if they are crucial (and not a lot). This way we minimize `using ...` statements and tutorials are more self-contained.

**Comment by harisorgn** [comment]
I've included instructions on how to install by downloading and instantiating a `Project.toml` containing all relevant packages : 
https://neuroblox.github.io/NeurobloxDocsHost/dev/install/
