### ISSUE TITLE
DDE or ODE for Jansen-Rit in Getting Started section?

### ISSUE THREAD

**Issue by gabrevaya** [Neuroblox/NeurobloxDocsHost#14]
Currently, in [Example 2](https://github.com/Neuroblox/NeurobloxDocsHost/blob/main/docs/src/getting_started.md#example-2--building-a-brain-circuit-from-literature-using-neural-mass-models) of the Getting Started section, it says that the Jansen-Rit model allows delayed edges and that we would build a `DDEProblem`, but then we build an `ODEProblem` and solve it with `Tsit5`. In order to make it consistent, should we actually build a `DDEProblem` and then solve it with something like `MethodOfSteps(Tsit5())`, or avoid mentioning the DDEs at that moment, keep building the `ODEProblem`, and just mention the possibility of incorporating delays at the end of the example?

**Comment by harisorgn** [comment]
I'd say keep it ODE and introduce delays in another example later in the docs, this is Getting Started so let's keep it very basic.
