### ISSUE TITLE
ERROR: TypeError in Tutorial on resting state simulation using neural mass models

### ISSUE THREAD

**Issue by fmvoid** [Neuroblox/NeurobloxDocsHost#19]
In the Tutorial on resting state simulation using neural mass models, I get an error when I run the line:
`sys = structural_simplify(sys)
`

The error is:
`ERROR: TypeError: in keyword argument init, expected AbstractDataFrame, got a value of type Vector{Equation}
Stacktrace:
 [1] parameter_dependencies(sys::SDESystem)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/abstractsystem.jl:1348
 [2] ModelingToolkit.IndexCache(sys::SDESystem)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/index_cache.jl:319
 [3] macro expansion
   @ ~/.julia/packages/Setfield/PdKfV/src/sugar.jl:197 [inlined]
 [4] complete(sys::SDESystem; split::Bool)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/abstractsystem.jl:864
 [5] structural_simplify(sys::ODESystem, io::Nothing; simplify::Bool, split::Bool, allow_symbolic::Bool, allow_parameter::Bool, conservative::Bool, fully_determined::Bool, kwargs::@Kwargs{})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/systems.jl:43
 [6] structural_simplify
   @ ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/systems.jl:20 [inlined]
 [7] structural_simplify(sys::ODESystem)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/SjwiH/src/systems/systems.jl:20
 [8] top-level scope
   @ ~/Desktop/Projects/pd_model/example_3.jl:29`

When I run:
`println(typeof(sys))`

I get: `ODESystem` so I am not sure why the error messages say SDESystem?

Thank you for building and sharing this toolbox!

**Comment by hstrey** [comment]
Thanks for letting us know.  The neural mass models are indeed SDEs, so it should be an SDESystem.  What version of Neuroblox did you use?  The current version on JuliaHub is 0.4.2.

**Comment by fmvoid** [comment]
I am using version 0.4.2, I installed it via JuliaHub.
I am also using ModelingToolkit v9.33.0.

**Comment by hstrey** [comment]
I will check it out on Monday.  I know that we now restrict MTK to be 9.32
or less because of some type issues.  I hope this will be resolved soon.

**Comment by hstrey** [comment]
We just released Neuroblox 0.4.3, which should be available very soon on JuliaHub.  Unfortunately, to upgrade you need to do the full authentication process.  I tested the current release with the tutorial and it works for me.  Let me know if it works for you.  Btw, I looked at the execution time of Neuroblox vs The Virtual Brain (the tutorial was copied from the TVB).  Neuroblox simulates in 3.5s as compared to 129s using the Python implementation using the same solver.
