### ISSUE TITLE
Old version of Neuroblox when instantiating the docs

### ISSUE THREAD

**Issue by gabrevaya** [Neuroblox/NeurobloxDocsHost#7]
When instantiating the docs, a version of Neuroblox much older (v0.3) than the current release (0.4.2) is installed.

```julia
(docs) pkg> st
Status `~/Documents/Neuroblox/NeurobloxDocsHost/docs/Project.toml`
  [336ed68f] CSV v0.10.14
  [a93c6f00] DataFrames v1.6.1
⌃ [0c46a032] DifferentialEquations v7.11.0
  [e30172f5] Documenter v1.5.0
  [86223c79] Graphs v1.11.2
  [09f84164] HypothesisTests v0.11.0
  [626554b9] MetaGraphs v0.7.2
  [769b91e5] Neuroblox v0.3.0
  [91a5bcdd] Plots v1.40.5
  [9a3f8284] Random
  [10745b16] Statistics v1.10.0
```

Since the only [compat] entry that we have in the Project.toml is for Documenter, all other packages are installed in their most recent compatible versions in the registry. This means that the most recent Neuroblox version in the registry (in this case, the JuliaHubRegistry) might be v0.3. I've just checked it by installing Neuroblox in the recommended way for the public (from the readme):

```julia
using Pkg
Pkg.add("PkgAuthentication")
using PkgAuthentication
PkgAuthentication.install("juliahub.com")
Pkg.Registry.add()
Pkg.add("Neuroblox")
```

And indeed, it installs version v0.3. So it seems that since the first public release, Neuroblox hasn't been updated in the JuliaHubRegistry.

Since this issue is more general than just the docs, I'll create another issue in the main Neuroblox repo.

**Comment by hstrey** [comment]
that should be taken care of.  The JuliaHub version should now be 0.4.2
